### ISSUE TITLE
ES6 module exports  on .vue files

### ISSUE THREAD

**Issue by sylvainpolletvillard** [activewidgets/getlibs#1]
Hello and thank you for making this, it looks very promising.

I tried getlibs on a Vue + TypeScript project and got some trouble with single file components .vue files

index.html:
```html
<!DOCTYPE html>
<html>
<head>
	<script src="https://unpkg.com/getlibs"></script>
</head>
<body>
<div id="app">Loading...</div>

<script>
	System.import('./main.ts')
</script>
</body>
</html>
```

main.ts:
```typescript
import Vue from 'vue'
import App from './components/App.vue'

new Vue({
	el: '#app',
	render: h => h(App)
})
```

App.vue:
```vue
<template>
	<div id="app">
		Hello {{ name }}
	</div>
</template>

<script>
	export default {
		data(){
			return { name: "Vue" }
		}
	}
</script>
```

gives me
```
Error: module is not defined
  Evaluating http://localhost:5000/components/App.vue
  Evaluating http://localhost:5000/main.ts
  Loading ./main.ts`
```

The App.vue!transpiled file :
 ```
(function(System, SystemJS) {"use strict";

System.register([], function (_export, _context) {
	"use strict";

	return {
		setters: [],
		execute: function () {
			_export("default", {
				data: function data() {
					return { name: "Vue" };
				}
			});

			module.exports.template = "\r\n\t<div id=\"app\">\r\n\t\tHello {{ name }}\r\n\t</div>\r\n";
		}
	};
});
})(System, System);
```

It looks like it should export with `_export.template` instead of `module.exports.template`

**Comment by xkam** [comment]
At the moment .vue loader works only with es5/require() syntax. Basically it just tries to inject the template property into module.exports object. I'll see if I can do something simple for es6/typescript.

**Comment by xkam** [comment]
I've changed .vue loader so that ES6 import/export should work now. However it will be transpiled by babel instead of typescript at the moment. That I still have to fix.

**Comment by sylvainpolletvillard** [comment]
Thanks, I can confirm that it is now working with export default.
I let you close this issue when you are done

**Comment by sylvainpolletvillard** [comment]
Not sure if it is a regression or if it is not supported at the moment, but the `<style>` tags in the `.vue` files do not work.

**Comment by xkam** [comment]
This is a regression - will fix in the next release.

**Comment by xkam** [comment]
styles should work now in 0.0.11 (global only, scoped styles not supported yet).

**Comment by xkam** [comment]
.vue components are now transpiled by typescript (in .ts context). Added support for class-style components and decorators - https://github.com/activewidgets/getlibs-vue-hello-ts

**Comment by sylvainpolletvillard** [comment]
Excellent work ! I will definitely use this
