### ISSUE TITLE
Targeting specific version of a library

### ISSUE THREAD

**Issue by raibima** [activewidgets/getlibs#2]
How do I go about doing this?

**Comment by xkam** [comment]
`getlibs` is based on SystemJS, so you can just configure it the way you want, for example -

```js
System.config({
  map: {
    'vue': 'https://cdnjs.cloudflare.com/ajax/libs/vue/2.3.3/vue.min.js'
  }
});

System.import('./main.js');
```
The SystemJS docs are here - https://github.com/systemjs/systemjs/blob/master/docs/config-api.md

Look also to the custom configs that `getlibs` includes by default - https://github.com/activewidgets/getlibs/tree/master/config
